import { useCallback, useEffect, useRef, useState } from 'react'
import { listingApi } from '@/services/listingApi'
import { shopApi } from '@/services/shopApi'
import { eventApi } from '@/services/eventApi'
import { adaptBusiness, adaptEvent, adaptListing, adaptOpportunity } from '@/native/discovery/adapters'
import { toBusinessParams, toEventParams, toListingParams, toOpportunityParams } from '@/native/discovery/queries'
import type { NativeDiscoveryCardModel, NativeDiscoveryKind, NativeExploreQuery, NativeSectionState } from '@/native/discovery/types'
import { useCachedPublicContent } from './useCachedPublicContent'

export interface NativeExploreGroup { kind: NativeDiscoveryKind; heading: string; state: NativeSectionState<NativeDiscoveryCardModel[]> }
export interface NativeTypedResults { state: NativeSectionState<NativeDiscoveryCardModel[]>; hasMore: boolean; loadingMore: boolean; loadMoreError: Error | null; loadMore(): Promise<void> }
export interface NativeExploreViewModel { groups: NativeExploreGroup[]; typed: NativeTypedResults | null; refreshAll(): Promise<void> }
const headings: Record<NativeDiscoveryKind, string> = { listing: 'Listings', business: 'Businesses', event: 'Events', volunteer: 'Volunteer' }
const empty = <T,>(value: T | null): T[] => Array.isArray(value) ? value as T[] : []
const responseItems = <T,>(response: { data?: { items?: T[] } | T[] }): T[] => Array.isArray(response.data) ? response.data : response.data?.items ?? []
const cancelled = (error: unknown) => Boolean(error && typeof error === 'object' && ('code' in error && (error as { code?: string }).code === 'ERR_CANCELED'))

export function useNativeExplore(query: NativeExploreQuery): NativeExploreViewModel {
  const all = query.type === 'all'; const keySuffix = query.q || query.category || query.urgency || query.sort ? JSON.stringify(query) : ''
  const listingKey = keySuffix ? `listing:native-explore:${keySuffix}` : 'listing:native-explore-default'; const businessKey = keySuffix ? `business:native-explore:${keySuffix}` : 'business:native-explore-default'; const eventKey = keySuffix ? `event:native-explore:${keySuffix}` : 'event:native-explore-default'; const volunteerKey = keySuffix ? `listing:native-explore-volunteer:${keySuffix}` : 'listing:native-explore-volunteer-default'
  const listing = useCachedPublicContent(listingKey, useCallback(async () => responseItems(await listingApi.browse(toListingParams({ ...query, type: 'all' }))), [query]), { enabled: all, cachePolicy: keySuffix ? 'none' : 'public' }); const business = useCachedPublicContent(businessKey, useCallback(async () => responseItems(await shopApi.directory(toBusinessParams({ ...query, type: 'all' }))), [query]), { enabled: all, cachePolicy: keySuffix ? 'none' : 'public' }); const event = useCachedPublicContent(eventKey, useCallback(async () => responseItems(await eventApi.list(toEventParams({ ...query, type: 'all' }))), [query]), { enabled: all, cachePolicy: keySuffix ? 'none' : 'public' }); const volunteer = useCachedPublicContent(volunteerKey, useCallback(async () => responseItems(await listingApi.getOpportunities(toOpportunityParams({ ...query, type: 'all' }))), [query]), { enabled: all, cachePolicy: keySuffix ? 'none' : 'public' })
  const groups: NativeExploreGroup[] = [
    { kind: 'listing', heading: headings.listing, state: { status: listing.status, data: empty(listing.data).slice(0, 5).map(adaptListing), source: listing.source, cachedAt: listing.cachedAt, error: listing.error, retry: listing.refresh } }, { kind: 'business', heading: headings.business, state: { status: business.status, data: empty(business.data).slice(0, 5).map(adaptBusiness), source: business.source, cachedAt: business.cachedAt, error: business.error, retry: business.refresh } }, { kind: 'event', heading: headings.event, state: { status: event.status, data: empty(event.data).slice(0, 5).map((item) => adaptEvent(item)), source: event.source, cachedAt: event.cachedAt, error: event.error, retry: event.refresh } }, { kind: 'volunteer', heading: headings.volunteer, state: { status: volunteer.status, data: empty(volunteer.data).slice(0, 5).map(adaptOpportunity), source: volunteer.source, cachedAt: volunteer.cachedAt, error: volunteer.error, retry: volunteer.refresh } },
  ]
  const typedModel = useTyped(query); const typed = query.type === 'all' ? null : typedModel; const refreshAll = async () => { await Promise.all([listing.refresh(), business.refresh(), event.refresh(), volunteer.refresh()]) }; return { groups, typed, refreshAll }
}

function useTyped(query: NativeExploreQuery): NativeTypedResults {
  const [state, setState] = useState<NativeSectionState<NativeDiscoveryCardModel[]>>({ status: 'loading', data: [], error: null, retry: async () => undefined }); const [hasMore, setHasMore] = useState(false); const [nextCursor, setNextCursor] = useState<string | null>(null); const [loadingMore, setLoadingMore] = useState(false); const [loadMoreError, setLoadMoreError] = useState<Error | null>(null); const generation = useRef(0); const controller = useRef<AbortController | null>(null); const queryKey = JSON.stringify(query)
  const request = useCallback(async (cursor?: string) => { const isMore = Boolean(cursor); const requestGeneration = generation.current; controller.current?.abort(); const abort = new AbortController(); controller.current = abort; if (isMore) { setLoadingMore(true); setLoadMoreError(null) } else setState((previous) => ({ ...previous, status: 'loading', error: null })); try { const params = query.type === 'listings' ? toListingParams(query) : query.type === 'businesses' ? toBusinessParams(query) : query.type === 'events' ? toEventParams(query) : toOpportunityParams(query); if (cursor) params.cursor = cursor; const response = query.type === 'listings' ? await listingApi.browse(params, { signal: abort.signal }) : query.type === 'businesses' ? await shopApi.directory(params, { signal: abort.signal }) : query.type === 'events' ? await eventApi.list(params, { signal: abort.signal }) : await listingApi.getOpportunities(params, { signal: abort.signal }); if (requestGeneration !== generation.current || abort.signal.aborted) return; const items = responseItems(response); const mapped = items.map((item) => query.type === 'listings' ? adaptListing(item) : query.type === 'businesses' ? adaptBusiness(item) : query.type === 'events' ? adaptEvent(item) : adaptOpportunity(item)); const data = isMore ? [...state.data, ...mapped].filter((item, index, list) => list.findIndex((candidate) => `${candidate.kind}:${candidate.id}` === `${item.kind}:${item.id}`) === index) : mapped; const page = response.data as { has_more?: boolean; next_cursor?: string | null }; const validCursor = Boolean(page.has_more && page.next_cursor); setState({ status: data.length ? 'success' : 'empty', data, error: null, retry: async () => request() }); setHasMore(validCursor); setNextCursor(validCursor ? page.next_cursor! : null) } catch (error) { if (abort.signal.aborted || cancelled(error) || requestGeneration !== generation.current) return; const issue = error instanceof Error ? error : new Error(String(error)); if (isMore) setLoadMoreError(issue); else setState((previous) => ({ ...previous, status: 'error', error: issue })) } finally { if (isMore) setLoadingMore(false) } }, [query, state.data])
  useEffect(() => { generation.current += 1; setHasMore(false); setNextCursor(null); setLoadMoreError(null); void request(); return () => controller.current?.abort() }, [queryKey])
  const loadMore = useCallback(async () => { if (!loadingMore && hasMore && nextCursor) await request(nextCursor) }, [hasMore, loadingMore, nextCursor, request]); return { state, hasMore, loadingMore, loadMoreError, loadMore }
}
