import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { listingApi } from '@/services/listingApi'
import { shopApi } from '@/services/shopApi'
import { eventApi } from '@/services/eventApi'
import { adaptBusiness, adaptEvent, adaptListing, adaptOpportunity } from '@/native/discovery/adapters'
import { toBusinessParams, toEventParams, toListingParams, toOpportunityParams } from '@/native/discovery/queries'
import type { NativeDiscoveryCardModel, NativeDiscoveryKind, NativeExploreQuery, NativeSectionState } from '@/native/discovery/types'
import { useCachedPublicContent } from './useCachedPublicContent'

export interface NativeExploreGroup { kind: NativeDiscoveryKind; heading: string; state: NativeSectionState<NativeDiscoveryCardModel[]> }
export interface NativeTypedResults { state: NativeSectionState<NativeDiscoveryCardModel[]>; hasMore: boolean; loadingMore: boolean; loadMoreError: Error | null; refineMessage: string | null; loadMore(): Promise<void> }
export interface NativeExploreViewModel { groups: NativeExploreGroup[]; typed: NativeTypedResults | null; refreshAll(): Promise<void> }
const headings: Record<NativeDiscoveryKind, string> = { listing: 'Listings', business: 'Businesses', event: 'Events', volunteer: 'Volunteer' }
const items = <T,>(response: { data?: { items?: T[] } | T[] }): T[] => Array.isArray(response.data) ? response.data : response.data?.items ?? []
const empty = <T,>(value: T | null): T[] => Array.isArray(value) ? value as T[] : []
const cancelled = (error: unknown) => Boolean(error && typeof error === 'object' && 'code' in error && (error as { code?: string }).code === 'ERR_CANCELED')

export function useNativeExplore(query: NativeExploreQuery): NativeExploreViewModel {
  const queryKey = JSON.stringify(query); const { q, type, category, urgency, sort, mode, near } = query; const all = type === 'all'; const isDefault = !q && !category && !urgency && !sort && mode === 'list' && !near
  const requestQuery = useMemo(() => ({ q, type, category, urgency, sort, mode, near }), [q, type, category, urgency, sort, mode, near])
  const key = (kind: string, fallback: string) => isDefault ? fallback : `${kind}:native-explore:${queryKey}`; const options = { enabled: all, cachePolicy: isDefault ? 'public' as const : 'none' as const }
  const listing = useCachedPublicContent(key('listing', 'listing:native-explore-default'), useCallback(async () => items(await listingApi.browse(toListingParams({ ...requestQuery, type: 'all' }))), [requestQuery]), options)
  const business = useCachedPublicContent(key('business', 'business:native-explore-default'), useCallback(async () => items(await shopApi.directory(toBusinessParams({ ...requestQuery, type: 'all' }))), [requestQuery]), options)
  const event = useCachedPublicContent(key('event', 'event:native-explore-default'), useCallback(async () => items(await eventApi.list(toEventParams({ ...requestQuery, type: 'all' }))), [requestQuery]), options)
  const volunteer = useCachedPublicContent(key('listing', 'listing:native-explore-volunteer-default'), useCallback(async () => items(await listingApi.getOpportunities(toOpportunityParams({ ...requestQuery, type: 'all' }))), [requestQuery]), options)
  const groups: NativeExploreGroup[] = [
    { kind: 'listing', heading: headings.listing, state: { status: listing.status, data: empty(listing.data).slice(0, 5).map(adaptListing), source: listing.source, cachedAt: listing.cachedAt, error: listing.error, retry: listing.refresh } },
    { kind: 'business', heading: headings.business, state: { status: business.status, data: empty(business.data).slice(0, 5).map(adaptBusiness), source: business.source, cachedAt: business.cachedAt, error: business.error, retry: business.refresh } },
    { kind: 'event', heading: headings.event, state: { status: event.status, data: empty(event.data).slice(0, 5).map((item) => adaptEvent(item)), source: event.source, cachedAt: event.cachedAt, error: event.error, retry: event.refresh } },
    { kind: 'volunteer', heading: headings.volunteer, state: { status: volunteer.status, data: empty(volunteer.data).slice(0, 5).map(adaptOpportunity), source: volunteer.source, cachedAt: volunteer.cachedAt, error: volunteer.error, retry: volunteer.refresh } },
  ]
  const typedModel = useTyped(requestQuery, !all); const refreshAll = async () => { await Promise.allSettled([listing.refresh(), business.refresh(), event.refresh(), volunteer.refresh()]) }; return { groups, typed: all ? null : typedModel, refreshAll }
}

function useTyped(query: NativeExploreQuery, enabled: boolean): NativeTypedResults {
  const queryKey = JSON.stringify(query); const stateRef = useRef<NativeSectionState<NativeDiscoveryCardModel[]>>({ status: 'loading', data: [], source: null, cachedAt: null, error: null, retry: async () => undefined }); const [state, setState] = useState(stateRef.current); stateRef.current = state; const [hasMore, setHasMore] = useState(false); const [nextCursor, setNextCursor] = useState<string | null>(null); const [loadingMore, setLoadingMore] = useState(false); const [loadMoreError, setLoadMoreError] = useState<Error | null>(null); const [refineMessage, setRefineMessage] = useState<string | null>(null); const generation = useRef(0); const controller = useRef<AbortController | null>(null)
  const request = useCallback(async (cursor?: string) => { if (!enabled) return; const more = Boolean(cursor); const current = generation.current; controller.current?.abort(); const abort = new AbortController(); controller.current = abort; if (more) { setLoadingMore(true); setLoadMoreError(null) } else setState((previous) => ({ ...previous, status: 'loading', error: null })); try { const params = query.type === 'listings' ? toListingParams(query) : query.type === 'businesses' ? toBusinessParams(query) : query.type === 'events' ? toEventParams(query) : toOpportunityParams(query); if (cursor) params.cursor = cursor; const response = query.type === 'listings' ? await listingApi.browse(params, { signal: abort.signal }) : query.type === 'businesses' ? await shopApi.directory(params, { signal: abort.signal }) : query.type === 'events' ? await eventApi.list(params, { signal: abort.signal }) : await listingApi.getOpportunities(params, { signal: abort.signal }); if (current !== generation.current || abort.signal.aborted) return; const mapped = items(response).map((item) => query.type === 'listings' ? adaptListing(item) : query.type === 'businesses' ? adaptBusiness(item) : query.type === 'events' ? adaptEvent(item) : adaptOpportunity(item)); const data = more ? [...stateRef.current.data, ...mapped].filter((item, index, list) => list.findIndex((candidate) => `${candidate.kind}:${candidate.id}` === `${item.kind}:${item.id}`) === index) : mapped; const page = response.data as { has_more?: boolean; next_cursor?: string | null }; const validCursor = Boolean(page.has_more && page.next_cursor); setRefineMessage(query.type === 'businesses' && page.has_more && !page.next_cursor ? 'Refine your search to narrow businesses' : null); setState({ status: data.length ? 'success' : 'empty', data, source: 'network', cachedAt: null, error: null, retry: () => request() }); setHasMore(validCursor); setNextCursor(validCursor ? page.next_cursor! : null) } catch (error) { if (abort.signal.aborted || cancelled(error) || current !== generation.current) return; const issue = error instanceof Error ? error : new Error(String(error)); if (more) setLoadMoreError(issue); else setState((previous) => ({ ...previous, status: 'error', error: issue, retry: () => request() })) } finally { if (more) setLoadingMore(false) } }, [enabled, query])
  useEffect(() => { if (!enabled) return; generation.current += 1; setHasMore(false); setNextCursor(null); setLoadMoreError(null); setRefineMessage(null); void request(); return () => controller.current?.abort() }, [enabled, queryKey, request]); const loadMore = useCallback(async () => { if (enabled && !loadingMore && hasMore && nextCursor) await request(nextCursor) }, [enabled, loadingMore, hasMore, nextCursor, request]); return { state, hasMore, loadingMore, loadMoreError, refineMessage, loadMore }
}
