"""add_saved_listings

Revision ID: 27b10e00f66d
Revises: 82dcea7bf563
Create Date: 2026-04-11 16:25:15.442732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b10e00f66d'
down_revision: Union[str, Sequence[str], None] = '82dcea7bf563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_saved_listing_user')
    )
    op.create_index('idx_saved_listings_listing', 'saved_listings', ['listing_id'], unique=False)
    op.create_index('idx_saved_listings_user', 'saved_listings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_saved_listings_user', table_name='saved_listings')
    op.drop_index('idx_saved_listings_listing', table_name='saved_listings')
    op.drop_table('saved_listings')
    # ### end Alembic commands ###
