"""add event submission and payment fields

Revision ID: 5d6016f29cb1
Revises: b875850b1df3
Create Date: 2026-04-17 15:05:19.310291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6016f29cb1'
down_revision: Union[str, Sequence[str], None] = 'b875850b1df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('submitted_by_name', sa.String(length=150), nullable=True))
    op.add_column('events', sa.Column('submitted_by_email', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('is_nonprofit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('events', sa.Column('nonprofit_doc_url', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('paid', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'paid')
    op.drop_column('events', 'stripe_session_id')
    op.drop_column('events', 'nonprofit_doc_url')
    op.drop_column('events', 'is_nonprofit')
    op.drop_column('events', 'submitted_by_email')
    op.drop_column('events', 'submitted_by_name')
    # ### end Alembic commands ###
