"""add_volunteers_and_talent_tables

Revision ID: 67ae05d6f046
Revises: cc20f8bfadd0
Create Date: 2026-04-05 00:32:09.397961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ae05d6f046'
down_revision: Union[str, Sequence[str], None] = 'cc20f8bfadd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('available_time', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_talent_category', 'talent', ['category'], unique=False)
    op.create_index('idx_talent_created', 'talent', ['created_at'], unique=False)
    op.create_table('volunteers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('available_time', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_volunteers_created', 'volunteers', ['created_at'], unique=False)
    op.create_table('talent_inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('talent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('preferred_date', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['talent_id'], ['talent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_talent_inquiries_talent', 'talent_inquiries', ['talent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_talent_inquiries_talent', table_name='talent_inquiries')
    op.drop_table('talent_inquiries')
    op.drop_index('idx_volunteers_created', table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_index('idx_talent_created', table_name='talent')
    op.drop_index('idx_talent_category', table_name='talent')
    op.drop_table('talent')
    # ### end Alembic commands ###
