"""add_events_and_connectors

Revision ID: 6bda391c6ebd
Revises: 67ae05d6f046
Create Date: 2026-04-05 17:13:29.045031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bda391c6ebd'
down_revision: Union[str, Sequence[str], None] = '67ae05d6f046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types explicitly (models use create_type=False)
    op.execute("CREATE TYPE event_category AS ENUM ('COMMUNITY', 'MUSIC', 'ART', 'FOOD', 'MARKET', 'HISTORIC', 'OUTDOOR', 'EDUCATION')")
    op.execute("CREATE TYPE event_status AS ENUM ('ACTIVE', 'CANCELLED', 'PAST')")
    op.execute("CREATE TYPE connector_type AS ENUM ('ICS', 'RSS', 'HTML')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', postgresql.ENUM('ICS', 'RSS', 'HTML', name='connector_type', create_type=False), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('category', postgresql.ENUM('COMMUNITY', 'MUSIC', 'ART', 'FOOD', 'MARKET', 'HISTORIC', 'OUTDOOR', 'EDUCATION', name='event_category', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_count', sa.Integer(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connectors_active', 'event_connectors', ['is_active'], unique=False)
    op.create_index('idx_connectors_type', 'event_connectors', ['type'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('category', postgresql.ENUM('COMMUNITY', 'MUSIC', 'ART', 'FOOD', 'MARKET', 'HISTORIC', 'OUTDOOR', 'EDUCATION', name='event_category', create_type=False), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('connector_id', sa.UUID(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'CANCELLED', 'PAST', name='event_status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['event_connectors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', 'connector_id', name='uq_event_source_connector')
    )
    op.create_index('idx_events_category', 'events', ['category'], unique=False)
    op.create_index('idx_events_connector', 'events', ['connector_id'], unique=False)
    op.create_index('idx_events_start_date', 'events', ['start_date'], unique=False)
    op.create_index('idx_events_status', 'events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_status', table_name='events')
    op.drop_index('idx_events_start_date', table_name='events')
    op.drop_index('idx_events_connector', table_name='events')
    op.drop_index('idx_events_category', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_connectors_type', table_name='event_connectors')
    op.drop_index('idx_connectors_active', table_name='event_connectors')
    op.drop_table('event_connectors')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS event_category")
    op.execute("DROP TYPE IF EXISTS event_status")
    op.execute("DROP TYPE IF EXISTS connector_type")
