"""add endorsements table

Revision ID: 6d676b9ef15d
Revises: 7d20e0c07eb3
Create Date: 2026-04-14 00:20:02.412372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d676b9ef15d'
down_revision: Union[str, Sequence[str], None] = '7d20e0c07eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endorsements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endorser_shop_id', sa.UUID(), nullable=False),
    sa.Column('endorsed_shop_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('endorser_shop_id != endorsed_shop_id', name='ck_no_self_endorsement'),
    sa.ForeignKeyConstraint(['endorsed_shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['endorser_shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endorser_shop_id', 'endorsed_shop_id', name='uq_endorsement_pair')
    )
    op.create_index('idx_endorsements_endorsed', 'endorsements', ['endorsed_shop_id'], unique=False)
    op.create_index('idx_endorsements_endorser', 'endorsements', ['endorser_shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_endorsements_endorser', table_name='endorsements')
    op.drop_index('idx_endorsements_endorsed', table_name='endorsements')
    op.drop_table('endorsements')
    # ### end Alembic commands ###
