"""add_email_to_volunteers_and_talent

Revision ID: 82dcea7bf563
Revises: 08722eb32386
Create Date: 2026-04-11 14:53:48.672637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82dcea7bf563'
down_revision: Union[str, Sequence[str], None] = '08722eb32386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talent', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('volunteers', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'email')
    op.drop_column('talent', 'email')
    # ### end Alembic commands ###
