"""add photo_url to talent and volunteer

Revision ID: b875850b1df3
Revises: 6d676b9ef15d
Create Date: 2026-04-14 21:10:43.161147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b875850b1df3'
down_revision: Union[str, Sequence[str], None] = '6d676b9ef15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talent', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('volunteers', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'photo_url')
    op.drop_column('talent', 'photo_url')
    # ### end Alembic commands ###
