"""add_ad_pricing_and_sponsor_payment_fields

Revision ID: bd7851b8c93e
Revises: 5dd097e7b9dc
Create Date: 2026-04-09 21:20:10.236691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7851b8c93e'
down_revision: Union[str, Sequence[str], None] = '5dd097e7b9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('placement', sa.String(length=50), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ad_pricing_active', 'ad_pricing', ['is_active'], unique=False)
    op.add_column('sponsors', sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
    op.add_column('sponsors', sa.Column('stripe_payment_intent', sa.String(length=255), nullable=True))
    op.add_column('sponsors', sa.Column('paid', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('sponsors', sa.Column('approved', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('sponsors', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('sponsors', sa.Column('contact_name', sa.String(length=200), nullable=True))
    op.add_column('sponsors', sa.Column('starts_at', sa.DateTime(), nullable=True))
    op.add_column('sponsors', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('sponsors', sa.Column('pricing_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsors', 'pricing_id')
    op.drop_column('sponsors', 'expires_at')
    op.drop_column('sponsors', 'starts_at')
    op.drop_column('sponsors', 'contact_name')
    op.drop_column('sponsors', 'contact_email')
    op.drop_column('sponsors', 'approved')
    op.drop_column('sponsors', 'paid')
    op.drop_column('sponsors', 'stripe_payment_intent')
    op.drop_column('sponsors', 'stripe_session_id')
    op.drop_index('idx_ad_pricing_active', table_name='ad_pricing')
    op.drop_table('ad_pricing')
    # ### end Alembic commands ###
