"""initial_schema

Revision ID: cc20f8bfadd0
Revises: 
Create Date: 2026-04-04 00:14:18.269663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc20f8bfadd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create shops first WITHOUT the circular FK to users
    op.create_table('shops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', name='shop_status', create_type=True), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('guidelines_accepted', sa.Boolean(), nullable=False),
    sa.Column('guidelines_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shops_admin', 'shops', ['admin_user_id'], unique=False)
    op.create_index('idx_shops_status', 'shops', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', postgresql.ENUM('COMMUNITY_ADMIN', 'SHOP_ADMIN', 'SHOP_EMPLOYEE', name='user_role'), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_shop_id', 'users', ['shop_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role_title', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employees_available', 'employees', ['shop_id', 'is_available'], unique=False)
    op.create_index('idx_employees_shop', 'employees', ['shop_id'], unique=False)
    op.create_table('guidelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('OFFER', 'REQUEST', name='listing_type'), nullable=False),
    sa.Column('category', postgresql.ENUM('STAFF', 'MATERIALS', 'EQUIPMENT', name='listing_category'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('urgency', postgresql.ENUM('NORMAL', 'URGENT', 'CRITICAL', name='urgency_level'), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'FULFILLED', 'EXPIRED', 'DELETED', name='listing_status'), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('interest_count', sa.Integer(), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_listings_category', 'listings', ['category'], unique=False)
    op.create_index('idx_listings_created_at', 'listings', ['created_at'], unique=False)
    op.create_index('idx_listings_expiry', 'listings', ['expiry_date'], unique=False)
    op.create_index('idx_listings_feed', 'listings', ['status', 'urgency', 'created_at'], unique=False)
    op.create_index('idx_listings_shop_id', 'listings', ['shop_id'], unique=False)
    op.create_index('idx_listings_status', 'listings', ['status'], unique=False)
    op.create_index('idx_listings_type', 'listings', ['type'], unique=False)
    op.create_index('idx_listings_urgency', 'listings', ['urgency'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('REGISTRATION_SUBMITTED', 'REGISTRATION_APPROVED', 'REGISTRATION_REJECTED', 'LISTING_INTEREST', 'NEW_MESSAGE', 'LISTING_EXPIRING', 'NEW_CRITICAL_LISTING', 'NEW_URGENT_LISTING', 'SHOP_SUSPENDED', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.Text(), nullable=False),
    sa.Column('auth_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index('idx_push_subs_user', 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'user_id', name='uq_interest_listing_user')
    )
    op.create_index('idx_interests_listing', 'interests', ['listing_id'], unique=False)
    op.create_index('idx_interests_user', 'interests', ['user_id'], unique=False)
    op.create_table('listing_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_listing_images_listing', 'listing_images', ['listing_id'], unique=False)
    op.create_table('message_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('participant_a', sa.UUID(), nullable=False),
    sa.Column('participant_b', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_a'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_b'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'participant_a', 'participant_b', name='uq_thread_listing_participants')
    )
    op.create_index('idx_threads_last_message', 'message_threads', ['last_message_at'], unique=False)
    op.create_index('idx_threads_participant_a', 'message_threads', ['participant_a'], unique=False)
    op.create_index('idx_threads_participant_b', 'message_threads', ['participant_b'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_thread', 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_index('idx_messages_unread', 'messages', ['thread_id', 'read_at'], unique=False)
    # Add deferred FK: shops.admin_user_id -> users.id (circular dependency)
    op.create_foreign_key('fk_shops_admin_user', 'shops', 'users', ['admin_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_unread', table_name='messages')
    op.drop_index('idx_messages_thread', table_name='messages')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_threads_participant_b', table_name='message_threads')
    op.drop_index('idx_threads_participant_a', table_name='message_threads')
    op.drop_index('idx_threads_last_message', table_name='message_threads')
    op.drop_table('message_threads')
    op.drop_index('idx_listing_images_listing', table_name='listing_images')
    op.drop_table('listing_images')
    op.drop_index('idx_interests_user', table_name='interests')
    op.drop_index('idx_interests_listing', table_name='interests')
    op.drop_table('interests')
    op.drop_index('idx_push_subs_user', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_index('idx_notifications_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_listings_urgency', table_name='listings')
    op.drop_index('idx_listings_type', table_name='listings')
    op.drop_index('idx_listings_status', table_name='listings')
    op.drop_index('idx_listings_shop_id', table_name='listings')
    op.drop_index('idx_listings_feed', table_name='listings')
    op.drop_index('idx_listings_expiry', table_name='listings')
    op.drop_index('idx_listings_created_at', table_name='listings')
    op.drop_index('idx_listings_category', table_name='listings')
    op.drop_table('listings')
    op.drop_table('guidelines')
    op.drop_index('idx_employees_shop', table_name='employees')
    op.drop_index('idx_employees_available', table_name='employees')
    op.drop_table('employees')
    op.drop_index('idx_users_shop_id', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_constraint('fk_shops_admin_user', 'shops', type_='foreignkey')
    op.drop_index('idx_shops_status', table_name='shops')
    op.drop_index('idx_shops_admin', table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
