"""add_success_stories

Revision ID: dc5876dac567
Revises: 27b10e00f66d
Create Date: 2026-04-11 16:30:27.571873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5876dac567'
down_revision: Union[str, Sequence[str], None] = '27b10e00f66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('success_stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_index('idx_success_stories_featured', 'success_stories', ['is_featured'], unique=False)
    op.create_index('idx_success_stories_listing', 'success_stories', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_success_stories_listing', table_name='success_stories')
    op.drop_index('idx_success_stories_featured', table_name='success_stories')
    op.drop_table('success_stories')
    # ### end Alembic commands ###
