import type { NativeExploreQuery, NativeExploreType } from './types'
const types: NativeExploreType[] = ['all', 'listings', 'businesses', 'events', 'bender', 'volunteer']
const listingCategories = ['staff', 'materials', 'equipment']; const eventCategories = ['community', 'music', 'art', 'food', 'market', 'historic', 'outdoor', 'education']; const sorts = ['urgency_desc', 'created_desc', 'expiry_asc']
const valid = (value: string | null, values: string[]) => value && values.includes(value) ? value : null
const categoryFor = (type: NativeExploreType, value: string | null) => type === 'listings' ? valid(value, listingCategories) : type === 'events' ? valid(value, eventCategories) : type === 'bender' || type === 'volunteer' ? null : value?.trim() || null
const urgencyFor = (type: NativeExploreType, value: NativeExploreQuery['urgency']) => type === 'all' || type === 'listings' || type === 'volunteer' ? value : null
const sortFor = (type: NativeExploreType, value: string | null) => type === 'listings' || type === 'volunteer' ? valid(value, sorts) : null
const mapModeFor = (type: NativeExploreType, value: NativeExploreQuery['mode']) => (type === 'all' || type === 'businesses') && value === 'map' ? 'map' as const : 'list' as const
export function parseNativeExploreQuery(params: URLSearchParams): NativeExploreQuery { const rawType = params.get('type') as NativeExploreType; const type = types.includes(rawType) ? rawType : 'all'; const rawUrgency = params.get('urgency'); const urgency = rawUrgency === 'urgent' || rawUrgency === 'normal' ? rawUrgency : null; return { q: params.get('q')?.trim() ?? '', type, category: categoryFor(type, params.get('category')), urgency: urgencyFor(type, urgency), sort: sortFor(type, params.get('sort')), mode: mapModeFor(type, params.get('mode') === 'map' ? 'map' : 'list'), near: type === 'businesses' && params.get('near') === 'true' } }
export function serializeNativeExploreQuery(query: NativeExploreQuery): URLSearchParams { const params = new URLSearchParams(); const category = categoryFor(query.type, query.category); const urgency = urgencyFor(query.type, query.urgency); const sort = sortFor(query.type, query.sort); const mode = mapModeFor(query.type, query.mode); if (query.q.trim()) params.set('q', query.q.trim()); if (query.type !== 'all') params.set('type', query.type); if (category) params.set('category', category); if (urgency) params.set('urgency', urgency); if (sort) params.set('sort', sort); if (mode === 'map') params.set('mode', mode); if (query.type === 'businesses' && query.near) params.set('near', 'true'); return params }
type Params = Record<string, string | number | boolean | undefined>
const search = (query: NativeExploreQuery): Params => ({ search: query.q || undefined }); const allLimit = (query: NativeExploreQuery): Params => query.type === 'all' ? { limit: 5 } : {}; const listingCategory = (query: NativeExploreQuery) => listingCategories.includes(query.category ?? '') ? query.category! : undefined; const eventCategory = (query: NativeExploreQuery) => eventCategories.includes(query.category ?? '') ? query.category! : undefined; const sort = (query: NativeExploreQuery) => sorts.includes(query.sort ?? '') ? query.sort! : undefined
export function toListingParams(query: NativeExploreQuery): Params { return { ...search(query), category: listingCategory(query), urgency: query.urgency || undefined, sort: sort(query), ...allLimit(query) } }
export function toBusinessParams(query: NativeExploreQuery): Params { return { ...search(query), business_type: query.type === 'businesses' || query.type === 'all' ? query.category || undefined : undefined, ...allLimit(query) } }
export function toEventParams(query: NativeExploreQuery): Params { return { ...search(query), category: eventCategory(query), ...allLimit(query) } }
export function toOpportunityParams(query: NativeExploreQuery): Params { return { ...search(query), urgency: query.urgency || undefined, sort: sort(query), ...allLimit(query) } }
