import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { readFileSync } from 'node:fs'
import { NativeDiscoveryCard } from './NativeDiscoveryCard'
import { NativeFilterChip } from './NativeFilterChip'
import { NativeResultGroup } from './NativeResultGroup'
import { NativeSearchBar } from './NativeSearchBar'
import { NativeUrgentCard } from './NativeUrgentCard'
import { NativeFilterSheet } from './NativeFilterSheet'
import { NativePageHeader } from './NativePageHeader'
import { NativeQuickAction } from './NativeQuickAction'
import { NativeSectionHeader } from './NativeSectionHeader'
import { PermissionPrimer } from '../PermissionPrimer'

const item = { id: 'listing-1', kind: 'listing' as const, label: 'Generator', title: 'Power generator needed', supportingText: 'Community request', thumbnailUrl: null, targetPath: '/listing/listing-1', coordinates: null, urgent: true }
const nativeCss = readFileSync('src/styles/native.css', 'utf8')
const indexHtml = readFileSync('index.html', 'utf8')
const cssRules = [...nativeCss.matchAll(/([^{}]+)\{([^{}]*)\}/g)].map(([, selectors, body]) => ({ selectors: selectors.split(',').map((selector) => selector.trim()), body }))
const cssRule = (selector: string) => cssRules.filter((rule) => rule.selectors.includes(selector)).map((rule) => rule.body).join('\n')

describe('native UI primitives', () => {
  afterEach(cleanup)
  it('controls search submit and clear through presentation callbacks', () => {
    const onChange = vi.fn(); const onSubmit = vi.fn(); const onClear = vi.fn()
    render(<NativeSearchBar value="books" label="Search" placeholder="Search listings" onChange={onChange} onSubmit={onSubmit} onClear={onClear} />)
    fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'book' } }); fireEvent.submit(screen.getByRole('searchbox').closest('form')!)
    fireEvent.click(screen.getByRole('button', { name: /clear/i }))
    expect(onChange).toHaveBeenCalledWith('book'); expect(onSubmit).toHaveBeenCalledOnce(); expect(onClear).toHaveBeenCalledOnce()
  })
  it('announces urgency and preserves a direct destination', () => {
    const onOpen = vi.fn(); render(<NativeUrgentCard item={item} onOpen={onOpen} />)
    expect(screen.getByText(/urgent need/i)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: /generator/i })); expect(onOpen).toHaveBeenCalledWith('/listing/listing-1')
  })
  it('labels an active removable filter', () => {
    const onRemove = vi.fn(); render(<NativeFilterChip label="Urgent" selected removable onRemove={onRemove} />)
    fireEvent.click(screen.getByRole('button', { name: /remove urgent filter/i })); expect(onRemove).toHaveBeenCalledOnce()
  })
  it('renders result status, one h2, and retry action', () => {
    const onRetry = vi.fn(); render(<NativeResultGroup heading="Listings" status="error" onRetry={onRetry}>children</NativeResultGroup>)
    expect(screen.getAllByRole('heading', { level: 2 })).toHaveLength(1); fireEvent.click(screen.getByRole('button', { name: /retry/i })); expect(onRetry).toHaveBeenCalledOnce()
  })
  it('sets fixed image dimensions on discovery cards', () => {
    render(<NativeDiscoveryCard item={{ ...item, urgent: false, thumbnailUrl: 'https://example.com/a.jpg' }} onOpen={vi.fn()} />)
    expect(screen.getByRole('img')).toHaveAttribute('width', '96'); expect(screen.getByRole('img')).toHaveAttribute('height', '96')
  })
  it('keeps interactive targets at least 44 points and includes the full wordmark', () => {
    const onRemove = vi.fn()
    render(<><NativeFilterChip label="Urgent" removable onRemove={onRemove} /><NativePageHeader title="Home" /></>)
    expect(screen.getAllByRole('button', { name: /remove urgent filter/i }).at(-1)).toHaveClass('native-control')
    expect(screen.getByLabelText('The Bend Community')).toHaveTextContent('The Bend')
  })
  it('renders loading and empty result states', () => {
    const { rerender } = render(<NativeResultGroup heading="Listings" status="loading" onRetry={vi.fn()}>items</NativeResultGroup>)
    expect(screen.getByText(/loading/i)).toBeInTheDocument()
    rerender(<NativeResultGroup heading="Listings" status="empty" onRetry={vi.fn()}>items</NativeResultGroup>)
    expect(screen.getByText(/no results/i)).toBeInTheDocument()
  })

  it('uses a skeleton for section-local loading feedback', () => {
    render(<NativeResultGroup heading="Loading" status="loading" onRetry={vi.fn()}>{null}</NativeResultGroup>)
    expect(document.querySelector('.native-skeleton')).toHaveClass('native-skeleton')
  })
  it('exposes one concise loading announcement and keeps the skeleton decorative', () => {
    render(<NativeResultGroup heading="Loading" status="loading" onRetry={vi.fn()}>{null}</NativeResultGroup>)
    expect(screen.getAllByRole('status')).toHaveLength(1)
    expect(screen.getByRole('status')).toHaveTextContent('Loading…')
    expect(document.querySelector('.native-skeleton')).toHaveAttribute('aria-hidden', 'true')
  })

  it('marks discovery images as lazy', () => {
    render(<NativeDiscoveryCard item={{ ...item, thumbnailUrl: '/image.jpg' }} onOpen={vi.fn()} />)
    expect(screen.getByRole('img')).toHaveAttribute('loading', 'lazy')
  })
  it('replaces failed discovery media with a type-specific Lucide fallback', () => {
    render(<NativeDiscoveryCard item={{ ...item, kind: 'event', thumbnailUrl: '/broken.jpg' }} onOpen={vi.fn()} />)
    const image = screen.getByRole('img')
    fireEvent.error(image)
    expect(screen.queryByRole('img')).toBeNull()
    expect(document.querySelector('[data-fallback-icon="event"]')).toBeInTheDocument()
    expect(document.querySelector('[data-fallback-icon="event"] svg')).toBeInTheDocument()
  })
  it('recovers discovery media when a new thumbnail URL arrives', () => {
    const { rerender } = render(<NativeDiscoveryCard item={{ ...item, thumbnailUrl: '/broken.jpg' }} onOpen={vi.fn()} />)
    fireEvent.error(screen.getByRole('img'))
    expect(screen.queryByRole('img')).toBeNull()
    rerender(<NativeDiscoveryCard item={{ ...item, thumbnailUrl: '/new.jpg' }} onOpen={vi.fn()} />)
    expect(screen.getByRole('img')).toHaveAttribute('src', '/new.jpg')
  })
  it('keeps header identity and account controls icon-only', () => {
    render(<NativePageHeader title="Home" isAuthenticated onAccount={vi.fn()} onNotifications={vi.fn()} />)
    expect(screen.getByRole('button', { name: 'Account' })).toHaveClass('native-header-icon')
    expect(screen.getByRole('button', { name: 'Notifications' })).toHaveClass('native-header-icon')
    expect(screen.getByRole('button', { name: 'Account' })).toHaveTextContent('')
    expect(screen.getByRole('button', { name: 'Notifications' })).toHaveTextContent('')
  })
  it('defines responsive contracts for long native content and 44-point controls', () => {
    expect(cssRule('.native-app .native-filter-chip')).toMatch(/display:\s*inline-flex/)
    expect(cssRule('.native-app .native-filter-chip')).toMatch(/max-width:\s*100%/)
    expect(cssRule('.native-app .native-filter-chip')).toMatch(/overflow-wrap:\s*anywhere/)
    expect(cssRule('.native-app .native-filter-chip > button')).toMatch(/width:\s*44px/)
    expect(cssRule('.native-app .native-filter-chip > button')).toMatch(/height:\s*44px/)
    expect(cssRule('.native-app .native-discovery-card')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-urgent-card')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-discovery-card img')).toMatch(/object-fit:\s*cover/)
    expect(cssRule('.native-app .native-thumbnail')).toMatch(/width:\s*96px/)
    expect(cssRule('.native-app .native-thumbnail')).toMatch(/height:\s*96px/)
    expect(cssRule('.native-app .native-search-bar')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-search-bar input')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-search-bar button')).toMatch(/width:\s*44px/)
    expect(cssRule('.native-app .native-search-bar button')).toMatch(/height:\s*44px/)
    expect(cssRule('.native-app .native-map-marker-list button')).toMatch(/min-width:\s*44px/)
    expect(cssRule('.native-app .native-map-marker-list button')).toMatch(/overflow-wrap:\s*anywhere/)
  })
  it('gives cards deliberate flexible layouts and all native buttons a 44-point floor', () => {
    expect(cssRule('.native-app .native-discovery-card')).toMatch(/gap:\s*var\(--native-space-3\)/)
    expect(cssRule('.native-app .native-discovery-card > span')).toMatch(/flex:\s*1 1 auto/)
    expect(cssRule('.native-app .native-discovery-card > span')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-urgent-card')).toMatch(/flex-direction:\s*column/)
    expect(cssRule('.native-app .native-urgent-card')).toMatch(/gap:\s*var\(--native-space-2\)/)
    expect(cssRule('.native-app button')).toMatch(/min-width:\s*44px/)
    expect(cssRule('.native-app button')).toMatch(/min-height:\s*44px/)
    expect(cssRule('.native-app a.native-control')).toMatch(/min-width:\s*44px/)
    expect(cssRule('.native-app a.native-control')).toMatch(/min-height:\s*44px/)
    expect(cssRule('.native-app .native-sheet-backdrop > [role="dialog"] > button.native-control')).toMatch(/width:\s*44px/)
  })
  it('keeps extreme untrusted labels and reserved image placeholders in the DOM', () => {
    const longText = 'A'.repeat(320)
    const onOpen = vi.fn()
    render(<><NativeFilterChip label={longText} removable onRemove={vi.fn()} /><NativeDiscoveryCard item={{ ...item, title: longText, supportingText: longText, thumbnailUrl: null }} onOpen={onOpen} /><NativeUrgentCard item={{ ...item, title: longText, supportingText: longText }} onOpen={onOpen} /><NativeSearchBar value={longText} label="Search" placeholder="Search" onChange={vi.fn()} onSubmit={vi.fn()} onClear={vi.fn()} /><NativePageHeader title={longText} /><NativeQuickAction label={longText} onClick={vi.fn()} /><NativeSectionHeader heading={longText} actionLabel={longText} onAction={vi.fn()} /><PermissionPrimer title={longText} description={longText} onConfirm={vi.fn()}>{longText}</PermissionPrimer><div className="native-map-marker-list"><button type="button" className="native-control">{longText}</button></div></>)
    expect(screen.getByText(longText, { selector: '.native-filter-chip' })).toBeInTheDocument()
    expect(screen.getAllByText(longText).length).toBeGreaterThanOrEqual(8)
    expect(document.querySelector('.native-thumbnail')).toBeInTheDocument()
    expect(screen.getByRole('searchbox')).toHaveValue(longText)
    expect(screen.getByRole('button', { name: /clear search/i })).toHaveClass('native-control')
    expect(document.querySelector('.native-quick-action')).toHaveTextContent(longText)
    expect(document.querySelector('.native-map-marker-list button')).toHaveTextContent(longText)
  })
  it('uses the same reserved 96-point contract for discovery image and placeholder variants', () => {
    const { rerender } = render(<NativeDiscoveryCard item={{ ...item, thumbnailUrl: '/image.jpg' }} onOpen={vi.fn()} />)
    const image = screen.getByRole('img')
    expect(image).toHaveAttribute('width', '96')
    expect(image).toHaveAttribute('height', '96')
    expect(image).toHaveAttribute('loading', 'lazy')
    rerender(<NativeDiscoveryCard item={{ ...item, thumbnailUrl: null }} onOpen={vi.fn()} />)
    expect(document.querySelector('.native-thumbnail')).toHaveAttribute('aria-hidden', 'true')
  })
  it('defines the warm native visual system without leaking into web styles', () => {
    expect(indexHtml).toContain('viewport-fit=cover')
    expect(cssRule('.native-app')).toMatch(/font-family:\s*Inter/)
    expect(cssRule('.native-app .native-safe-area')).toMatch(/padding-top:\s*var\(--native-safe-top/)
    expect(cssRule('.native-app .native-page-header.native-safe-area')).toMatch(/padding-top:\s*calc\(10px\s*\+\s*var\(--native-safe-top\)/)
    expect(cssRule('.native-app .native-explore-title')).toMatch(/padding-top:\s*calc\(10px\s*\+\s*var\(--native-safe-top/)
    expect(cssRule('.native-app .native-page-header')).toMatch(/align-items:\s*stretch/)
    expect(cssRule('.native-app .native-page-header')).toMatch(/flex-wrap:\s*nowrap/)
    expect(cssRule('.native-app')).toMatch(/--native-nav-height:\s*72px/)
    expect(cssRule('.native-app .native-main')).toMatch(/padding-bottom:\s*calc\(88px\s*\+\s*var\(--native-safe-bottom\)/)
    expect(cssRule('.native-app .native-bottom-nav.native-safe-bottom')).toMatch(/padding-bottom:\s*var\(--native-safe-bottom/)
    expect(cssRule('.native-app .native-bottom-nav')).toMatch(/background:\s*var\(--native-elevated\)/)
    expect(cssRule('.native-app h1')).toMatch(/font-family:\s*Inter/)
    expect(cssRule('.native-app h2')).toMatch(/font-family:\s*Inter/)
    expect(cssRule('.native-app h3')).toMatch(/font-family:\s*Inter/)
    expect(cssRule('.native-app .native-header-top')).toMatch(/display:\s*flex/)
    expect(cssRule('.native-app .native-page-header')).toMatch(/padding:/)
    expect(cssRule('.native-app .native-search-bar')).toMatch(/height:\s*48px/)
    expect(cssRule('.native-app .native-page-header')).toMatch(/background:\s*var\(--native-page\)\s*!important/)
    expect(cssRule('.native-app .native-search-bar input')).toMatch(/background:\s*var\(--native-elevated\)\s*!important/)
    expect(cssRule('.native-app .native-page-header')).toMatch(/!important/)
    expect(cssRule('.native-app .native-search-bar input::placeholder')).toMatch(/color:\s*var\(--native-muted\)\s*!important/)
    expect(cssRule('.native-app .native-quick-actions')).toMatch(/grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/)
    expect(cssRule('.native-app .native-urgent-card')).toMatch(/background:\s*var\(--native-urgent-surface\)/)
    expect(cssRule('.native-app .native-safe-bottom')).toMatch(/padding-bottom:\s*var\(--native-safe-bottom/)
    expect(cssRule('.native-app .native-card-list')).toMatch(/gap:/)
    expect(cssRule('.native-app .native-discovery-card > span')).toMatch(/flex-direction:\s*column/)
    expect(cssRule('.native-app .native-discovery-card > span')).toMatch(/align-items:\s*flex-start/)
    expect(cssRule('.native-app .native-discovery-card > span')).toMatch(/text-align:\s*left/)
    expect(cssRule('.native-app .native-discovery-card > span > small')).toMatch(/text-transform:\s*uppercase/)
    expect(cssRule('.native-app .native-discovery-card > span > small')).toMatch(/color:\s*var\(--native-bronze\)/)
    expect(cssRule('.native-app .native-discovery-card > span > strong')).toMatch(/font-size:\s*14px/)
    expect(cssRule('.native-app .native-discovery-card > span > span')).toMatch(/font-size:\s*11px/)
    expect(cssRule('.native-app .native-home-scroll .native-card-list .native-discovery-card > span > small')).toMatch(/font-size:\s*9px/)
    expect(cssRule('.native-app .native-home-scroll .native-card-list .native-discovery-card > span > strong')).toMatch(/font-size:\s*12px/)
    expect(cssRule('.native-app .native-home-scroll .native-card-list .native-discovery-card > span > span')).toMatch(/font-size:\s*9px/)
    expect(cssRule('.native-app .native-discovery-card')).toMatch(/background:\s*var\(--native-card\)/)
    expect(cssRule('.native-app .native-discovery-card img')).toMatch(/border-radius:/)
    expect(cssRule('.native-app .native-home-scroll .native-card-list')).toMatch(/grid-template-columns:\s*repeat\(2,/)
    expect(cssRule('.native-app .native-urgent-row')).toMatch(/display:\s*flex/)
    expect(cssRule('.native-app .native-urgent-row img')).toMatch(/width:\s*64px/)
    expect(cssRule('.native-app .native-explore-scroll [role="tablist"]')).toMatch(/display:\s*flex/)
    expect(cssRule('.native-app .native-explore-scroll [role="tab"][aria-selected="true"]')).toMatch(/background:\s*var\(--native-primary\)/)
    expect(cssRule('.native-app .native-filter-sheet')).toMatch(/gap:/)
    expect(cssRule('.native-app .native-section-header h2')).toMatch(/font-size:/)
    expect(cssRule('.native-app .native-section-header button')).toMatch(/color:\s*var\(--native-bronze\)/)
    expect(cssRule('.native-app .native-bottom-nav-item[aria-current="page"]')).toMatch(/color:\s*var\(--native-primary\)/)
    expect(cssRule('.native-app .native-quick-action > svg')).toMatch(/background:/)
    expect(cssRule('.native-app .native-explore-scroll [role="tab"]')).toMatch(/flex:\s*0 0 auto/)
    expect(cssRule('.native-app .native-brand > strong')).toMatch(/-webkit-text-size-adjust:\s*none/)
    expect(cssRule('.native-app .native-brand > strong')).toMatch(/font-size:\s*calc\(21px\s*\*\s*var\(--native-fixed-text-scale\)\)/)
    expect(cssRule('.native-app .native-brand b')).toMatch(/font-size:\s*calc\(15px\s*\*\s*var\(--native-fixed-text-scale\)\)/)
    expect(cssRule('.native-app .native-brand small')).toMatch(/font-size:\s*calc\(11px\s*\*\s*var\(--native-fixed-text-scale\)\)/)
    expect(cssRule('.native-app .native-bottom-nav-item')).toMatch(/-webkit-text-size-adjust:\s*none/)
    expect(cssRule('.native-app .native-bottom-nav-item')).toMatch(/font-size:\s*calc\(16px\s*\*\s*var\(--native-fixed-text-scale\)\)/)
    expect(cssRule('.native-app .native-quick-action')).toMatch(/-webkit-text-size-adjust:\s*none/)
    expect(cssRule('.native-app .native-quick-action')).toMatch(/font-size:\s*calc\(11px\s*\*\s*var\(--native-fixed-text-scale\)\)/)
    expect(cssRule('.native-app .native-bottom-nav-item span')).toMatch(/text-overflow:\s*ellipsis/)
    expect(cssRule('.native-app .native-bottom-nav-item span')).toMatch(/width:\s*100%/)
    expect(cssRule('.native-app .native-bottom-nav-item span')).toMatch(/max-width:\s*100%/)
    expect(cssRule('.native-app .native-bottom-nav-item span')).toMatch(/white-space:\s*nowrap/)
    expect(cssRule('.native-app .native-explore-scroll [role="tab"]')).not.toMatch(/native-fixed-text-scale/)
    expect(cssRule('.native-app .native-card')).not.toMatch(/native-fixed-text-scale/)
    expect(cssRule('.native-app .native-bottom-nav-item')).toMatch(/flex:\s*1 1 0/)
    expect(cssRule('.native-app .native-thumbnail-fallback')).toMatch(/border-radius:/)
    expect(cssRule('.native-app .native-explore-scroll')).toMatch(/padding:/)
    expect(cssRule('.native-app .native-explore-controls')).toMatch(/display:\s*flex/)
    expect(cssRule('.native-app .native-home-scroll')).toMatch(/padding:\s*0\s*18px/)
    expect(cssRule('.native-app .native-explore-scroll')).toMatch(/padding:\s*0\s*18px/)
    expect(cssRule('.native-app .native-partner-button')).toMatch(/display:\s*inline-flex/)
    expect(cssRule('.dark .native-app')).toMatch(/--native-page:/)
  })
  it('focuses, traps, and closes the filter sheet while returning focus', () => {
    const trigger = document.createElement('button'); trigger.textContent = 'Open'; document.body.append(trigger); const onClose = vi.fn()
    const { rerender } = render(<NativeFilterSheet open title="Filters" onClose={onClose} returnFocusRef={{ current: trigger }}><button className="native-control">Apply</button></NativeFilterSheet>)
    const close = screen.getByRole('button', { name: /close filters/i }); const apply = screen.getByRole('button', { name: 'Apply' })
    expect(close).toHaveFocus(); apply.focus(); fireEvent.keyDown(document, { key: 'Tab' }); expect(close).toHaveFocus(); close.focus(); fireEvent.keyDown(document, { key: 'Tab', shiftKey: true }); expect(apply).toHaveFocus()
    fireEvent.keyDown(document, { key: 'Escape' }); expect(onClose).toHaveBeenCalledOnce()
    fireEvent.mouseDown(screen.getByRole('presentation')); expect(onClose).toHaveBeenCalledTimes(2)
    rerender(<NativeFilterSheet open={false} title="Filters" onClose={onClose} returnFocusRef={{ current: trigger }}><button>Apply</button></NativeFilterSheet>); expect(trigger).toHaveFocus(); trigger.remove()
  })
})
