import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { readFileSync } from 'node:fs'
import { NativeDiscoveryCard } from './NativeDiscoveryCard'
import { NativeFilterChip } from './NativeFilterChip'
import { NativeResultGroup } from './NativeResultGroup'
import { NativeSearchBar } from './NativeSearchBar'
import { NativeUrgentCard } from './NativeUrgentCard'
import { NativeFilterSheet } from './NativeFilterSheet'
import { NativePageHeader } from './NativePageHeader'
import { NativeQuickAction } from './NativeQuickAction'
import { NativeSectionHeader } from './NativeSectionHeader'
import { PermissionPrimer } from '../PermissionPrimer'

const item = { id: 'listing-1', kind: 'listing' as const, label: 'Generator', title: 'Power generator needed', supportingText: 'Community request', thumbnailUrl: null, mediaFit: 'cover' as const, targetPath: '/listing/listing-1', coordinates: null, urgent: true }
const nativeCss = readFileSync('src/styles/native.css', 'utf8')
const indexHtml = readFileSync('index.html', 'utf8')
const cssRules = [...nativeCss.matchAll(/([^{}]+)\{([^{}]*)\}/g)].map(([, selectors, body]) => ({ selectors: selectors.split(',').map((selector) => selector.trim()), body }))
const cssRule = (selector: string) => cssRules.filter((rule) => rule.selectors.includes(selector)).map((rule) => rule.body).join('\n')

describe('native UI primitives', () => {
  afterEach(cleanup)
  it('keeps native auth control geometry scoped and keyboard-visible', () => {
    for (const selector of ['.native-auth-password-toggle', '.native-auth-inline-action', '.native-auth-guideline-action', '.native-auth-consent-control']) {
      const rule = cssRule(`.native-app ${selector}`)
      expect(rule).toMatch(/min-width:\s*44px/)
      expect(rule).toMatch(/min-height:\s*44px/)
      expect(nativeCss).toContain(`.native-app ${selector}:focus-visible`)
    }
  })
  it('controls search submit and clear through presentation callbacks', () => {
    const onChange = vi.fn(); const onSubmit = vi.fn(); const onClear = vi.fn()
    render(<NativeSearchBar value="books" label="Search" placeholder="Search listings" onChange={onChange} onSubmit={onSubmit} onClear={onClear} />)
    fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'book' } }); fireEvent.submit(screen.getByRole('searchbox').closest('form')!)
    fireEvent.click(screen.getByRole('button', { name: /clear/i }))
    expect(onChange).toHaveBeenCalledWith('book'); expect(onSubmit).toHaveBeenCalledOnce(); expect(onClear).toHaveBeenCalledOnce()
  })
  it('announces urgency and preserves a direct destination', () => {
    const onOpen = vi.fn(); render(<NativeUrgentCard item={item} onOpen={onOpen} />)
    expect(screen.getByText(/urgent need/i)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: /generator/i })); expect(onOpen).toHaveBeenCalledWith('/listing/listing-1')
  })
  it('labels an active removable filter', () => {
    const onRemove = vi.fn(); render(<NativeFilterChip label="Urgent" selected removable onRemove={onRemove} />)
    fireEvent.click(screen.getByRole('button', { name: /remove urgent filter/i })); expect(onRemove).toHaveBeenCalledOnce()
  })
  it('renders result status, one h2, and retry action', () => {
    const onRetry = vi.fn(); render(<NativeResultGroup heading="Listings" status="error" onRetry={onRetry}>children</NativeResultGroup>)
    expect(screen.getAllByRole('heading', { level: 2 })).toHaveLength(1); fireEvent.click(screen.getByRole('button', { name: /retry/i })); expect(onRetry).toHaveBeenCalledOnce()
  })
  it('sets fixed image dimensions on discovery cards', () => {
    render(<NativeDiscoveryCard item={{ ...item, urgent: false, thumbnailUrl: 'https://example.com/a.jpg' }} onOpen={vi.fn()} />)
    expect(screen.getByRole('img')).toHaveAttribute('width', '96'); expect(screen.getByRole('img')).toHaveAttribute('height', '96')
  })
  it('exposes explicit media fit and preserves stable fallback geometry', () => {
    const { rerender } = render(<NativeDiscoveryCard item={{ ...item, kind: 'business', mediaFit: 'contain', thumbnailUrl: '/logo.png', urgent: false }} onOpen={vi.fn()} />)
    expect(screen.getByRole('img')).toHaveAttribute('data-media-fit', 'contain')
    expect(screen.getByRole('img')).toHaveClass('native-discovery-media--contain')
    expect(cssRule('.native-app .native-discovery-card img.native-discovery-media--contain')).toMatch(/object-fit:\s*contain/)
    fireEvent.error(screen.getByRole('img'))
    const fallback = document.querySelector('.native-thumbnail-fallback')
    expect(fallback).toHaveAttribute('data-media-fit', 'contain')
    expect(fallback).toHaveClass('native-discovery-media--contain')
    expect(fallback).toHaveClass('native-thumbnail')
    rerender(<NativeDiscoveryCard item={{ ...item, mediaFit: 'cover', thumbnailUrl: '/listing.jpg', urgent: false }} onOpen={vi.fn()} />)
    expect(screen.getByRole('img')).toHaveAttribute('data-media-fit', 'cover')
    expect(screen.getByRole('img')).toHaveClass('native-discovery-media--cover')
    expect(cssRule('.native-app .native-discovery-card img.native-discovery-media--cover')).toMatch(/object-fit:\s*cover/)
  })
  it('resolves backend upload paths before rendering discovery images', () => {
    render(<NativeDiscoveryCard item={{ ...item, urgent: false, thumbnailUrl: '/uploads/images/listing.jpg' }} onOpen={vi.fn()} />)
    expect(screen.getByRole('img')).toHaveAttribute('src', 'http://localhost:8000/uploads/images/listing.jpg')
  })
  it('resolves backend upload paths before rendering urgent images', () => {
    render(<NativeUrgentCard item={{ ...item, thumbnailUrl: '/uploads/images/urgent.jpg' }} onOpen={vi.fn()} />)
    expect(document.querySelector('.native-urgent-row img')).toHaveAttribute('src', 'http://localhost:8000/uploads/images/urgent.jpg')
  })
  it('keeps interactive targets at least 44 points and includes the full wordmark', () => {
    const onRemove = vi.fn()
    render(<><NativeFilterChip label="Urgent" removable onRemove={onRemove} /><NativePageHeader title="Home" /></>)
    expect(screen.getAllByRole('button', { name: /remove urgent filter/i }).at(-1)).toHaveClass('native-control')
    expect(screen.getByLabelText('The Bend Community')).toHaveTextContent('The Bend')
  })
  it('renders loading and empty result states', () => {
    const { rerender } = render(<NativeResultGroup heading="Listings" status="loading" onRetry={vi.fn()}>items</NativeResultGroup>)
    expect(screen.getByText(/loading/i)).toBeInTheDocument()
    rerender(<NativeResultGroup heading="Listings" status="empty" onRetry={vi.fn()}>items</NativeResultGroup>)
    expect(screen.getByText(/no results/i)).toBeInTheDocument()
  })

  it('uses a skeleton for section-local loading feedback', () => {
    render(<NativeResultGroup heading="Loading" status="loading" onRetry={vi.fn()}>{null}</NativeResultGroup>)
    expect(document.querySelector('.native-skeleton')).toHaveClass('native-skeleton')
  })
  it('exposes one concise loading announcement and keeps the skeleton decorative', () => {
    render(<NativeResultGroup heading="Loading" status="loading" onRetry={vi.fn()}>{null}</NativeResultGroup>)
    expect(screen.getAllByRole('status')).toHaveLength(1)
    expect(screen.getByRole('status')).toHaveTextContent('Loading…')
    expect(document.querySelector('.native-skeleton')).toHaveAttribute('aria-hidden', 'true')
  })

  it('marks discovery images as lazy', () => {
    render(<NativeDiscoveryCard item={{ ...item, thumbnailUrl: '/image.jpg' }} onOpen={vi.fn()} />)
    expect(screen.getByRole('img')).toHaveAttribute('loading', 'lazy')
  })
  it('replaces failed discovery media with a type-specific Lucide fallback', () => {
    render(<NativeDiscoveryCard item={{ ...item, kind: 'event', thumbnailUrl: '/broken.jpg' }} onOpen={vi.fn()} />)
    const image = screen.getByRole('img')
    fireEvent.error(image)
    expect(screen.queryByRole('img')).toBeNull()
    expect(document.querySelector('[data-fallback-icon="event"]')).toBeInTheDocument()
    expect(document.querySelector('[data-fallback-icon="event"] svg')).toBeInTheDocument()
  })
  it('renders a dedicated Bender fallback instead of the generic file glyph', () => {
    render(<NativeDiscoveryCard item={{ ...item, kind: 'bender' as never, label: 'Bender', title: 'Community update', supportingText: 'Pat Neighbor', thumbnailUrl: null }} onOpen={vi.fn()} />)
    expect(screen.getByRole('button', { name: 'Open Bender post by Pat Neighbor: Community update' })).toHaveClass('native-bender-discovery-card')
    const icon = document.querySelector('[data-fallback-icon="bender"] svg')
    expect(icon).toBeInTheDocument()
    expect(icon).toHaveClass('lucide-sparkles')
    expect(icon).not.toHaveClass('lucide-file-text')
  })
  it('treats a Bender discovery thumbnail as decorative within its labelled card', () => {
    render(<NativeDiscoveryCard item={{ ...item, kind: 'bender' as never, label: 'Bender', title: 'Community update', supportingText: 'Pat Neighbor', thumbnailUrl: '/post.jpg' }} onOpen={vi.fn()} />)
    expect(document.querySelector('img')).toHaveAttribute('alt', '')
  })
  it('recovers discovery media when a new thumbnail URL arrives', () => {
    const { rerender } = render(<NativeDiscoveryCard item={{ ...item, thumbnailUrl: '/broken.jpg' }} onOpen={vi.fn()} />)
    fireEvent.error(screen.getByRole('img'))
    expect(screen.queryByRole('img')).toBeNull()
    rerender(<NativeDiscoveryCard item={{ ...item, thumbnailUrl: '/new.jpg' }} onOpen={vi.fn()} />)
    expect(screen.getByRole('img')).toHaveAttribute('src', '/new.jpg')
  })
  it('renders authenticated header controls in notification then message order without Account', () => {
    render(<NativePageHeader title="Home" isAuthenticated onNotifications={vi.fn()} onMessages={vi.fn()} />)
    const actions = document.querySelector('.native-header-actions')!
    expect(within(actions).getByRole('button', { name: 'Notifications' })).toHaveClass('native-header-icon')
    expect(within(actions).getByRole('button', { name: 'Messages' })).toHaveClass('native-header-icon')
    expect(actions.querySelectorAll('button')).toHaveLength(2)
    expect(actions.querySelectorAll('button')[0]).toHaveAccessibleName('Notifications')
    expect(actions.querySelectorAll('button')[1]).toHaveAccessibleName('Messages')
    expect(within(actions).queryByRole('button', { name: 'Account' })).toBeNull()
  })
  it('defines responsive contracts for long native content and 44-point controls', () => {
    expect(cssRule('.native-app .native-filter-chip')).toMatch(/display:\s*inline-flex/)
    expect(cssRule('.native-app .native-filter-chip')).toMatch(/max-width:\s*100%/)
    expect(cssRule('.native-app .native-filter-chip')).toMatch(/overflow-wrap:\s*anywhere/)
    expect(cssRule('.native-app .native-filter-chip > button')).toMatch(/width:\s*44px/)
    expect(cssRule('.native-app .native-filter-chip > button')).toMatch(/height:\s*44px/)
    expect(cssRule('.native-app .native-discovery-card')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-urgent-card')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-discovery-card img')).toMatch(/object-fit:\s*cover/)
    expect(cssRule('.native-app .native-thumbnail')).toMatch(/width:\s*96px/)
    expect(cssRule('.native-app .native-thumbnail')).toMatch(/height:\s*96px/)
    expect(cssRule('.native-app .native-search-bar')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-search-bar input')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-search-bar button')).toMatch(/width:\s*44px/)
    expect(cssRule('.native-app .native-search-bar button')).toMatch(/height:\s*44px/)
    expect(cssRule('.native-app .native-map-marker-list button')).toMatch(/min-width:\s*44px/)
    expect(cssRule('.native-app .native-map-marker-list button')).toMatch(/overflow-wrap:\s*anywhere/)
  })
  it('keeps Explore tabs, panels, map controls, and Leaflet within native chrome', () => {
    expect(cssRule('.native-app .native-explore-type-tabs')).toMatch(/overflow-x:\s*auto/)
    expect(cssRule('.native-app .native-explore-type-tabs')).toMatch(/padding-inline-end:\s*var\(--native-space-4\)/)
    expect(cssRule('.native-app .native-explore-type-tabs button')).toMatch(/flex:\s*0 0 auto/)
    expect(cssRule('.native-app .native-explore-tabpanel')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-explore-tabpanel')).toMatch(/max-width:\s*100%/)
    expect(cssRule('.native-app .native-view-mode button')).toMatch(/min-width:\s*44px/)
    expect(cssRule('.native-app .native-view-mode button')).toMatch(/min-height:\s*44px/)
    expect(cssRule('.native-app .native-map-location-control')).toMatch(/min-width:\s*44px/)
    expect(cssRule('.native-app .native-map-location-control')).toMatch(/min-height:\s*44px/)
    expect(nativeCss).toContain('.native-app .native-explore-type-tabs button:focus-visible')
    expect(nativeCss).toContain('.native-app .native-view-mode button:focus-visible')
    expect(nativeCss).toContain('.native-app .native-map-location-control:focus-visible')
    expect(cssRule('.native-app .leaflet-container')).toMatch(/isolation:\s*isolate/)
    expect(cssRule('.native-app .leaflet-container')).toMatch(/z-index:\s*0/)
  })
  it('gives cards deliberate flexible layouts and all native buttons a 44-point floor', () => {
    expect(cssRule('.native-app .native-discovery-card')).toMatch(/gap:\s*var\(--native-space-3\)/)
    expect(cssRule('.native-app .native-discovery-card > span')).toMatch(/flex:\s*1 1 auto/)
    expect(cssRule('.native-app .native-discovery-card > span')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-urgent-card')).toMatch(/flex-direction:\s*column/)
    expect(cssRule('.native-app .native-urgent-card')).toMatch(/gap:\s*var\(--native-space-2\)/)
    expect(cssRule('.native-app button')).toMatch(/min-width:\s*44px/)
    expect(cssRule('.native-app button')).toMatch(/min-height:\s*44px/)
    expect(cssRule('.native-app a.native-control')).toMatch(/min-width:\s*44px/)
    expect(cssRule('.native-app a.native-control')).toMatch(/min-height:\s*44px/)
    expect(cssRule('.native-app .native-sheet-backdrop > [role="dialog"] > button.native-control')).toMatch(/width:\s*44px/)
  })
  it('keeps Bender previews full-width, readable, and bounded on compact screens', () => {
    expect(cssRule('.native-app .native-bender-list')).toMatch(/display:\s*grid/)
    expect(cssRule('.native-app .native-bender-list')).toMatch(/gap:\s*var\(--native-space-3\)/)
    expect(cssRule('.native-app .native-bender-card')).toMatch(/display:\s*grid/)
    expect(cssRule('.native-app .native-bender-card')).toMatch(/grid-template-columns:\s*88px\s+minmax\(0,\s*1fr\)/)
    expect(cssRule('.native-app .native-bender-card')).toMatch(/width:\s*100%/)
    expect(cssRule('.native-app .native-bender-card')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-bender-media')).toMatch(/width:\s*88px/)
    expect(cssRule('.native-app .native-bender-media')).toMatch(/height:\s*88px/)
    expect(cssRule('.native-app .native-bender-media')).toMatch(/object-fit:\s*cover/)
    expect(cssRule('.native-app .native-bender-copy')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-bender-meta')).toMatch(/flex-wrap:\s*wrap/)
    expect(cssRule('.native-app .native-bender-meta strong')).toMatch(/overflow-wrap:\s*anywhere/)
    expect(cssRule('.native-app .native-bender-meta strong')).toMatch(/white-space:\s*normal/)
    expect(cssRule('.native-app .native-bender-caption')).toMatch(/overflow-wrap:\s*anywhere/)
    expect(cssRule('.native-app .native-bender-discovery-card > span > strong')).toMatch(/-webkit-line-clamp:\s*3/)
    expect(cssRule('.native-app .native-bender-discovery-card > span > strong')).toMatch(/overflow:\s*hidden/)
  })
  it('keeps compact Bender post cards readable and touch-safe', () => {
    expect(cssRule('.native-app .native-bender-post-card')).toMatch(/width:\s*100%/)
    expect(cssRule('.native-app .native-bender-post-card')).toMatch(/overflow-wrap:\s*anywhere/)
    expect(cssRule('.native-app .native-bender-post-card .native-bender-caption')).toMatch(/white-space:\s*pre-wrap/)
    expect(cssRule('.native-app .native-bender-post-card .native-bender-actions')).toMatch(/flex-wrap:\s*wrap/)
    expect(cssRule('.native-app .native-bender-post-card .native-bender-post-action')).toMatch(/min-width:\s*44px/)
    expect(cssRule('.native-app .native-bender-post-card .native-bender-post-action')).toMatch(/min-height:\s*44px/)
  })
  it('renders Partners as one bounded manual swipe carousel', () => {
    expect(cssRule('.native-app .native-partner-track')).toMatch(/display:\s*grid/)
    expect(cssRule('.native-app .native-partner-track')).toMatch(/grid-auto-flow:\s*column/)
    expect(cssRule('.native-app .native-partner-track')).toMatch(/grid-auto-columns:\s*100%/)
    expect(cssRule('.native-app .native-partner-track')).toMatch(/overflow-x:\s*auto/)
    expect(cssRule('.native-app .native-partner-track')).toMatch(/scroll-snap-type:\s*x mandatory/)
    expect(cssRule('.native-app .native-partner-slide')).toMatch(/scroll-snap-align:\s*start/)
    expect(cssRule('.native-app .native-partner-slide')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-partner-card')).toMatch(/width:\s*100%/)
    expect(cssRule('.native-app .native-partner-card')).toMatch(/min-width:\s*0/)
    expect(cssRule('.native-app .native-partner-card')).toMatch(/overflow-wrap:\s*anywhere/)
    expect(cssRule('.native-app .native-partner-logo img')).toMatch(/object-fit:\s*contain/)
    expect(cssRule('.native-app .native-partner-description')).toMatch(/-webkit-line-clamp:\s*3/)
    expect(cssRule('.native-app .native-partner-pagination')).toMatch(/display:\s*flex/)
  })
  it('keeps partner steps and discovery media controls touch-safe and explicit', () => {
    expect(cssRule('.native-app .native-partner-controls')).toMatch(/display:\s*flex/)
    expect(cssRule('.native-app .native-partner-step')).toMatch(/min-width:\s*44px/)
    expect(cssRule('.native-app .native-partner-step')).toMatch(/min-height:\s*44px/)
    expect(cssRule('.native-app .native-partner-step')).toMatch(/border:/)
    expect(cssRule('.native-app .native-partner-step:disabled')).toMatch(/color:/)
    expect(cssRule('.native-app .native-partner-step:disabled')).toMatch(/background:/)
    expect(nativeCss).toContain('.native-app .native-partner-step:focus-visible')
    expect(cssRule('.native-app .native-discovery-media--contain')).toMatch(/object-fit:\s*contain/)
    expect(cssRule('.native-app .native-discovery-media--cover')).toMatch(/object-fit:\s*cover/)
    expect(cssRule('.native-app .native-partner-logo img')).toMatch(/object-fit:\s*contain/)
  })
  it('routes the full native Bender feed through adaptive semantic colors', () => {
    expect(cssRule('.native-app .native-bender-page')).toMatch(/background:\s*var\(--native-page\)\s*!important/)
    expect(cssRule('.native-app .native-bender-surface')).toMatch(/background:\s*var\(--native-card\)\s*!important/)
    expect(cssRule('.native-app .native-bender-muted-surface')).toMatch(/background:\s*var\(--native-page\)\s*!important/)
    expect(cssRule('.native-app .native-bender-primary')).toMatch(/color:\s*var\(--native-text\)\s*!important/)
    expect(cssRule('.native-app .native-bender-secondary')).toMatch(/color:\s*var\(--native-muted\)\s*!important/)
    expect(cssRule('.native-app .native-bender-border')).toMatch(/border-color:\s*var\(--native-border\)\s*!important/)
  })
  it('keeps extreme untrusted labels and reserved image placeholders in the DOM', () => {
    const longText = 'A'.repeat(320)
    const onOpen = vi.fn()
    render(<><NativeFilterChip label={longText} removable onRemove={vi.fn()} /><NativeDiscoveryCard item={{ ...item, title: longText, supportingText: longText, thumbnailUrl: null }} onOpen={onOpen} /><NativeUrgentCard item={{ ...item, title: longText, supportingText: longText }} onOpen={onOpen} /><NativeSearchBar value={longText} label="Search" placeholder="Search" onChange={vi.fn()} onSubmit={vi.fn()} onClear={vi.fn()} /><NativePageHeader title={longText} /><NativeQuickAction label={longText} onClick={vi.fn()} /><NativeSectionHeader heading={longText} actionLabel={longText} onAction={vi.fn()} /><PermissionPrimer title={longText} description={longText} onConfirm={vi.fn()}>{longText}</PermissionPrimer><div className="native-map-marker-list"><button type="button" className="native-control">{longText}</button></div></>)
    expect(screen.getByText(longText, { selector: '.native-filter-chip' })).toBeInTheDocument()
    expect(screen.getAllByText(longText).length).toBeGreaterThanOrEqual(8)
    expect(document.querySelector('.native-thumbnail')).toBeInTheDocument()
    expect(screen.getByRole('searchbox')).toHaveValue(longText)
    expect(screen.getByRole('button', { name: /clear search/i })).toHaveClass('native-control')
    expect(document.querySelector('.native-quick-action')).toHaveTextContent(longText)
    expect(document.querySelector('.native-map-marker-list button')).toHaveTextContent(longText)
  })
  it('uses the same reserved 96-point contract for discovery image and placeholder variants', () => {
    const { rerender } = render(<NativeDiscoveryCard item={{ ...item, thumbnailUrl: '/image.jpg' }} onOpen={vi.fn()} />)
    const image = screen.getByRole('img')
    expect(image).toHaveAttribute('width', '96')
    expect(image).toHaveAttribute('height', '96')
    expect(image).toHaveAttribute('loading', 'lazy')
    rerender(<NativeDiscoveryCard item={{ ...item, thumbnailUrl: null }} onOpen={vi.fn()} />)
    expect(document.querySelector('.native-thumbnail')).toHaveAttribute('aria-hidden', 'true')
  })
  it('applies the native content scale to reading text while keeping compact chrome fixed', () => {
    expect(cssRule('.native-app')).toMatch(/-webkit-text-size-adjust:\s*var\(--native-content-text-scale,\s*100%\)/)
    expect(cssRule('.native-app')).toMatch(/(?:^|;)\s*text-size-adjust:\s*var\(--native-content-text-scale,\s*100%\)/)
    for (const selector of ['.native-app .native-brand', '.native-app .native-quick-action', '.native-app .native-bottom-nav-item']) {
      expect(cssRule(selector)).toMatch(/-webkit-text-size-adjust:\s*none/)
      expect(cssRule(selector)).toMatch(/(?:^|;)\s*text-size-adjust:\s*none/)
    }
    for (const selector of ['.native-app .native-card', '.native-app .native-auth-page', '.native-app .native-explore-scroll [role="tab"]']) {
      expect(cssRule(selector)).not.toMatch(/(?:-webkit-)?text-size-adjust:\s*none/)
    }
    expect(cssRule('.native-app .native-search-bar')).toMatch(/min-height:\s*48px/)
    expect(cssRule('.native-app .native-search-bar')).toMatch(/height:\s*auto/)
    expect(cssRule('.native-app .native-search-bar')).toMatch(/padding-block:\s*2px/)
    expect(cssRule('.native-app .native-bender-page input.native-bender-input')).toMatch(/min-height:\s*44px/)
    expect(cssRule('.native-app .native-bender-page input.native-bender-input')).toMatch(/height:\s*auto/)
  })
  it('defines the warm native visual system without leaking into web styles', () => {
    expect(indexHtml).toContain('viewport-fit=cover')
    expect(cssRule('.native-app')).toMatch(/font-family:\s*Inter/)
    expect(cssRule('.native-app')).toMatch(/--native-safe-top:\s*var\(--safe-area-inset-top,\s*env\(safe-area-inset-top,\s*0px\)\)/)
    expect(cssRule('.native-app')).toMatch(/--native-safe-bottom:\s*var\(--safe-area-inset-bottom,\s*env\(safe-area-inset-bottom,\s*0px\)\)/)
    expect(cssRule('.native-app .native-safe-area')).toMatch(/padding-top:\s*var\(--native-safe-top/)
    expect(cssRule('.native-app .native-page-header.native-safe-area')).toMatch(/padding-top:\s*calc\(10px\s*\+\s*var\(--native-safe-top\)/)
    expect(cssRule('.native-app .native-explore-title')).toMatch(/padding-top:\s*calc\(10px\s*\+\s*var\(--native-safe-top/)
    expect(cssRule('.native-app .native-status-bar-scrim')).toMatch(/position:\s*fixed/)
    expect(cssRule('.native-app .native-status-bar-scrim')).toMatch(/height:\s*var\(--native-safe-top\)/)
    expect(cssRule('.native-app .native-status-bar-scrim')).toMatch(/background:\s*var\(--native-page\)/)
    expect(cssRule('.native-app .native-status-bar-scrim')).toMatch(/pointer-events:\s*none/)
    expect(cssRule('.native-app .native-status-bar-scrim')).toMatch(/z-index:\s*50/)
    expect(cssRule('.native-app .native-explore-map')).toMatch(/isolation:\s*isolate/)
    expect(cssRule('.native-app .leaflet-container')).toMatch(/isolation:\s*isolate/)
    expect(cssRule('.native-app .leaflet-container')).toMatch(/z-index:\s*0/)
    expect(cssRule('.native-app .native-page-header')).toMatch(/align-items:\s*stretch/)
    expect(cssRule('.native-app .native-page-header')).toMatch(/flex-wrap:\s*nowrap/)
    expect(cssRule('.native-app')).toMatch(/--native-nav-height:\s*72px/)
    expect(cssRule('.native-app .native-main')).toMatch(/padding-bottom:\s*calc\(88px\s*\+\s*var\(--native-safe-bottom\)/)
    expect(cssRule('.native-app .native-auth-page')).toMatch(/min-height:\s*calc\(100dvh\s*-\s*var\(--native-safe-bottom\)\)/)
    expect(cssRule('.native-app .native-auth-page')).not.toMatch(/overflow:\s*hidden/)
    expect(cssRule('.native-app .native-bottom-nav.native-safe-bottom')).toMatch(/padding-bottom:\s*var\(--native-safe-bottom/)
    expect(cssRule('.native-app .native-bottom-nav')).toMatch(/background:\s*var\(--native-elevated\)/)
    expect(cssRule('.native-app h1')).toMatch(/font-family:\s*Inter/)
    expect(cssRule('.native-app h2')).toMatch(/font-family:\s*Inter/)
    expect(cssRule('.native-app h3')).toMatch(/font-family:\s*Inter/)
    expect(cssRule('.native-app .native-header-top')).toMatch(/display:\s*flex/)
    expect(cssRule('.native-app .native-page-header')).toMatch(/padding:/)
    expect(cssRule('.native-app .native-search-bar')).toMatch(/min-height:\s*48px/)
    expect(cssRule('.native-app .native-page-header')).toMatch(/background:\s*var\(--native-page\)\s*!important/)
    expect(cssRule('.native-app .native-search-bar input')).toMatch(/background:\s*var\(--native-elevated\)\s*!important/)
    expect(cssRule('.native-app .native-page-header')).toMatch(/!important/)
    expect(cssRule('.native-app .native-search-bar input::placeholder')).toMatch(/color:\s*var\(--native-muted\)\s*!important/)
    expect(cssRule('.native-app .native-quick-actions')).toMatch(/grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/)
    expect(cssRule('.native-app .native-urgent-card')).toMatch(/background:\s*var\(--native-urgent-surface\)/)
    expect(cssRule('.native-app .native-safe-bottom')).toMatch(/padding-bottom:\s*var\(--native-safe-bottom/)
    expect(cssRule('.native-app .native-card-list')).toMatch(/gap:/)
    expect(cssRule('.native-app .native-discovery-card > span')).toMatch(/flex-direction:\s*column/)
    expect(cssRule('.native-app .native-discovery-card > span')).toMatch(/align-items:\s*flex-start/)
    expect(cssRule('.native-app .native-discovery-card > span')).toMatch(/text-align:\s*left/)
    expect(cssRule('.native-app .native-discovery-card > span > small')).toMatch(/text-transform:\s*uppercase/)
    expect(cssRule('.native-app .native-discovery-card > span > small')).toMatch(/color:\s*var\(--native-bronze\)/)
    expect(cssRule('.native-app .native-discovery-card > span > strong')).toMatch(/font-size:\s*14px/)
    expect(cssRule('.native-app .native-discovery-card > span > span')).toMatch(/font-size:\s*11px/)
    expect(cssRule('.native-app .native-home-scroll .native-card-list .native-discovery-card > span > small')).toMatch(/font-size:\s*9px/)
    expect(cssRule('.native-app .native-home-scroll .native-card-list .native-discovery-card > span > strong')).toMatch(/font-size:\s*12px/)
    expect(cssRule('.native-app .native-home-scroll .native-card-list .native-discovery-card > span > span')).toMatch(/font-size:\s*9px/)
    expect(cssRule('.native-app .native-discovery-card')).toMatch(/background:\s*var\(--native-card\)/)
    expect(cssRule('.native-app .native-discovery-card img')).toMatch(/border-radius:/)
    expect(cssRule('.native-app .native-home-scroll .native-card-list')).toMatch(/grid-template-columns:\s*repeat\(2,/)
    expect(cssRule('.native-app .native-urgent-row')).toMatch(/display:\s*flex/)
    expect(cssRule('.native-app .native-urgent-row img')).toMatch(/width:\s*64px/)
    expect(cssRule('.native-app .native-explore-scroll [role="tablist"]')).toMatch(/display:\s*flex/)
    expect(cssRule('.native-app .native-explore-scroll [role="tab"][aria-selected="true"]')).toMatch(/background:\s*var\(--native-primary\)/)
    expect(cssRule('.native-app .native-filter-sheet')).toMatch(/gap:/)
    expect(cssRule('.native-app .native-section-header h2')).toMatch(/font-size:/)
    expect(cssRule('.native-app .native-section-header button')).toMatch(/color:\s*var\(--native-bronze\)/)
    expect(cssRule('.native-app .native-bottom-nav-item[aria-current="page"]')).toMatch(/color:\s*var\(--native-primary\)/)
    expect(cssRule('.native-app .native-quick-action > svg')).toMatch(/background:/)
    expect(cssRule('.native-app .native-explore-scroll [role="tab"]')).toMatch(/flex:\s*0 0 auto/)
    expect(cssRule('.native-app .native-brand > strong')).toMatch(/-webkit-text-size-adjust:\s*none/)
    expect(cssRule('.native-app .native-brand > strong')).toMatch(/font-size:\s*calc\(21px\s*\*\s*var\(--native-fixed-text-scale\)\)/)
    expect(cssRule('.native-app .native-brand b')).toMatch(/font-size:\s*calc\(15px\s*\*\s*var\(--native-fixed-text-scale\)\)/)
    expect(cssRule('.native-app .native-brand small')).toMatch(/font-size:\s*calc\(11px\s*\*\s*var\(--native-fixed-text-scale\)\)/)
    expect(cssRule('.native-app .native-bottom-nav-item')).toMatch(/-webkit-text-size-adjust:\s*none/)
    expect(cssRule('.native-app .native-bottom-nav-item')).toMatch(/font-size:\s*calc\(16px\s*\*\s*var\(--native-fixed-text-scale\)\)/)
    expect(cssRule('.native-app .native-quick-action')).toMatch(/-webkit-text-size-adjust:\s*none/)
    expect(cssRule('.native-app .native-quick-action')).toMatch(/font-size:\s*calc\(11px\s*\*\s*var\(--native-fixed-text-scale\)\)/)
    expect(cssRule('.native-app .native-bottom-nav-item span')).toMatch(/text-overflow:\s*ellipsis/)
    expect(cssRule('.native-app .native-bottom-nav-item span')).toMatch(/width:\s*100%/)
    expect(cssRule('.native-app .native-bottom-nav-item span')).toMatch(/max-width:\s*100%/)
    expect(cssRule('.native-app .native-bottom-nav-item span')).toMatch(/white-space:\s*nowrap/)
    expect(cssRule('.native-app .native-explore-scroll [role="tab"]')).not.toMatch(/native-fixed-text-scale/)
    expect(cssRule('.native-app .native-card')).not.toMatch(/native-fixed-text-scale/)
    expect(cssRule('.native-app .native-bottom-nav-item')).toMatch(/flex:\s*1 1 0/)
    expect(cssRule('.native-app .native-thumbnail-fallback')).toMatch(/border-radius:/)
    expect(cssRule('.native-app .native-explore-scroll')).toMatch(/padding:/)
    expect(cssRule('.native-app .native-explore-controls')).toMatch(/display:\s*flex/)
    expect(cssRule('.native-app .native-explore-controls > button:disabled')).toMatch(/opacity:/)
    expect(cssRule('.native-app .native-explore-controls > button:disabled')).toMatch(/cursor:\s*not-allowed/)
    expect(cssRule('.native-app .native-listing-image-nav')).toMatch(/min-width:\s*44px/)
    expect(cssRule('.native-app .native-listing-image-nav')).toMatch(/min-height:\s*44px/)
    expect(cssRule('.native-app .native-home-scroll')).toMatch(/padding:\s*0\s*18px/)
    expect(cssRule('.native-app .native-explore-scroll')).toMatch(/padding:\s*0\s*18px/)
    expect(cssRule('.native-app .native-partner-button')).toMatch(/display:\s*inline-flex/)
    expect(cssRule('.dark .native-app')).toMatch(/--native-page:/)
    expect(cssRule('.dark .native-app .native-themed-page')).toMatch(/background:\s*var\(--native-page\)/)
    expect(nativeCss).toMatch(/\.dark \.native-app \.native-themed-page \.bg-white[^{]*\{[^}]*background:\s*var\(--native-card\)/)
    expect(nativeCss).toMatch(/\.dark \.native-app \.native-themed-page \[class\*="text-gray-9"\][^{]*\{[^}]*color:\s*var\(--native-text\)/)
    expect(nativeCss).toMatch(/\.dark \.native-app \.native-themed-page (?:input|input,)[\s\S]*background:\s*var\(--native-elevated\)/)
  })
  it('focuses, traps, and closes the filter sheet while returning focus', () => {
    const trigger = document.createElement('button'); trigger.textContent = 'Open'; document.body.append(trigger); const onClose = vi.fn()
    const { rerender } = render(<NativeFilterSheet open title="Filters" closeLabel="Close filters" onClose={onClose} returnFocusRef={{ current: trigger }}><button className="native-control">Apply</button><a href="/guidelines">Read Guidelines</a></NativeFilterSheet>)
    const close = screen.getByRole('button', { name: /close filters/i }); const apply = screen.getByRole('button', { name: 'Apply' }); const link = screen.getByRole('link', { name: 'Read Guidelines' })
    expect(close).toHaveFocus(); link.focus(); fireEvent.keyDown(document, { key: 'Tab' }); expect(close).toHaveFocus(); close.focus(); fireEvent.keyDown(document, { key: 'Tab', shiftKey: true }); expect(link).toHaveFocus(); apply.focus()
    fireEvent.keyDown(document, { key: 'Escape' }); expect(onClose).toHaveBeenCalledOnce()
    fireEvent.mouseDown(screen.getByRole('presentation')); expect(onClose).toHaveBeenCalledTimes(2)
    rerender(<NativeFilterSheet open={false} title="Filters" closeLabel="Close filters" onClose={onClose} returnFocusRef={{ current: trigger }}><button>Apply</button></NativeFilterSheet>); expect(trigger).toHaveFocus(); trigger.remove()
  })
  it('keeps a Guidelines disclosure inside the sheet focus boundary', () => {
    render(<NativeFilterSheet open title="Community Guidelines" onClose={vi.fn()}><details><summary>On this page</summary></details></NativeFilterSheet>)
    const close = screen.getByRole('button', { name: 'Close Community Guidelines' })
    const summary = screen.getByText('On this page')
    summary.focus(); fireEvent.keyDown(document, { key: 'Tab' }); expect(close).toHaveFocus()
    close.focus(); fireEvent.keyDown(document, { key: 'Tab', shiftKey: true }); expect(summary).toHaveFocus()
  })
})
